#!/bin/bash

##FUNCTIONS
function help(){
	echo
	echo -e "doc2pdf <option>"
	echo -e "\t -p \t path, default path ./ "
	echo -e "\t -i \t install doc2pdf in system"
	echo
	echo -e "convert any file [docx, doc, xls, png]"
	echo 
}

function dependencies(){
	dependencies=(find lowriter pdftoppm)
	echo -e "[*]Check dependencies..."
	sleep 1
	for program in "${dependencies[@]}"; do
		if [ ! $( command -v $program ) ];
		then
    		if [ $(id -u) != 0 ];then
				echo -e "You must be root to install $dependencies"
				exit
			fi

			if [ $program == "pdftoppm" ];then
				add-apt-repository ppa:scribus/ppa -y
				apt-get update -y
				apt-get install poppler-utils -y
			fi

			if [ $program == "lowriter" ];then
				add-apt-repository ppa:libreoffice/ppa -y
				apt update
				apt install libreoffice
			fi
		fi
	done
}


function install(){
	if [ $(id -u) != 0 ];then
		echo -e "You must be root"
		exit 0
	fi

	if [ -d /usr/local/bin ];then 
		cp doc2pdf /usr/local/bin
		echo "[+] Installed"
	else
		echo "[-] Not found /usr/local/bin"
	fi
}

function main(){

	path=${PWD}

	if [ $1 ] && [ -d $1 ];then
		path=$1
    else
		echo $1 "Path not found"
		exit 0
	fi

	cd $path

	#Remove spaces
	find $path -name "* *" -type f | rename 's/ /_/g'

	#Convert any doc/docx
	lowriter --convert-to pdf *.docx 2>/dev/null
	lowriter --convert-to pdf *.doc 2>/dev/null
	lowriter --convert-to pdf *.xls 2>/dev/null
    lowriter --convert-to pdf *.png 2>/dev/null

	#Get first page 
	for i in *.pdf
	do
   		pdftoppm -jpeg -f 1 -l 1 $i $i
	done

	exit 0
}

##MAIN

dependencies

if [ $1 ];then

	case $1 in
		-i)
		    install
		;;
		-p)
			main $2
		;;
		*)
			help
		;; 
	esac
else
	help
fi


exit 0; 

